apiVersion: v1
kind: Secret
metadata:
  name: cold-backend-secret
  namespace: default
type: Opaque
stringData:
  db-password: "SecurePostgresPassword123"
  jwt-secret: "your-super-secret-jwt-key-change-this-in-production-minimum-32-characters"
