apiVersion: v1
kind: Service
metadata:
  name: cold-backend-monitoring
  namespace: default
  labels:
    app: cold-backend
    component: monitoring
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
    name: monitoring
  selector:
    app: cold-backend
